In [ ]:
#insatall numpy 

## pip
!pip install numpy
!conda install numpy

In [ ]:
import numpy as np

a = np.zeros(3)
a

array([0., 0., 0.])

In [ ]:
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
a = np.zeros((10,2))
a

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
a.shape

(10, 2)

In [ ]:
a = a.reshape(2,10)

In [ ]:
a

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
a = np.ones(1)

In [ ]:
a

array([1.])

In [ ]:
a = np.ones((10,20))

In [ ]:
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.]])

In [ ]:
a.shape

(10, 20)

In [ ]:
type(a)

numpy.ndarray

In [ ]:
a = [[1,2,3],[4,5,6],[7,6,9]]
type(a)

list

In [ ]:
a

[[1, 2, 3], [4, 5, 6], [7, 6, 9]]

In [ ]:
a.shape

AttributeError: ignored

In [ ]:
a = a.resahpe((3,3))

AttributeError: ignored

In [ ]:
a = np.array(a)

In [ ]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 6, 9]])

In [ ]:
type(a)

numpy.ndarray

In [ ]:
a.shape

(3, 3)

In [ ]:
a[1][2]

6

In [ ]:
a[:1]

array([[1, 2, 3]])

In [ ]:
a[:1, 1:]

array([[2, 3]])

In [ ]:
a = np.array([[1,2,3],[4,5,6],[7,6,9]], dtype='float32')
b = np.array([[1,2,3],[4,5,6],[7,6,9]], dtype='float32')

In [ ]:
a

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 6., 9.]], dtype=float32)

In [ ]:
b

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 6., 9.]], dtype=float32)

In [ ]:
b+5

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 11, 14]])

In [ ]:
b*5

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 30, 45]])

In [ ]:
b/2

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ],
       [3.5, 3. , 4.5]])

In [ ]:
b-5

array([[-4, -3, -2],
       [-1,  0,  1],
       [ 2,  1,  4]])

In [ ]:
a+b

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 12, 18]])

In [ ]:
a*b

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 36, 81]])

In [ ]:
np.matmul(a,b)

array([[ 30,  30,  42],
       [ 66,  69,  96],
       [ 94,  98, 138]])

In [ ]:
a@b

array([[ 30,  30,  42],
       [ 66,  69,  96],
       [ 94,  98, 138]])

In [ ]:
a/b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
a = np.sin(90)

In [ ]:
a

0.8939966636005579

In [ ]:
a = np.tan(45)

In [ ]:
a

1.6197751905438615

In [ ]:
print(np.min(b))
print(np.max(b))

1
9


In [ ]:
np.sum(b)

43

In [ ]:
b>5

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [ ]:
for i in b:
    print(i)

[1. 2. 3.]
[4. 5. 6.]
[7. 6. 9.]


In [ ]:
for i in b:
    for j in i:
        print(j)

1.0
2.0
3.0
4.0
5.0
6.0
7.0
6.0
9.0


In [ ]:
a = np.zeros((2,3,4))
a

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [ ]:
for i in a:
    print(i)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
for i in a:
    for j in i:
        print(j)

[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]


In [ ]:
count = 0
for i in a:
    for j in i:
        for k in j:
            count+=1
            print(k)

print(count)

0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
24


In [ ]:
shape = a.shape

In [ ]:
shape

(2, 3, 4)

In [ ]:
np.prod(shape)==count

True

In [ ]:
a = a.reshape(2,3)

ValueError: ignored

In [ ]:
a = a.reshape(8,3)
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
a = a.reshape(24,1)
a

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [ ]:
a = a.reshape(6,4)

In [ ]:
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])